#Git
- name: Install Git
  become: yes
  apt: state=latest name={{item}}
  with_items: 
    - git
  when: ansible_pkg_mgr == 'apt'

- name: Link git config
  become: no
  file: state=link src={{role_path}}/files/gitconfig dest="{{ lookup('env','HOME') }}/.gitconfig"
