#!/usr/bin/env sh
# Git global hook to ignore pre-commit hooks if we have not added any file to the staging area
# Useful since some hooks might be time-consuming (e.g. running lint in a big project)
# With thanks to https://stackoverflow.com/a/53722351

MODIFIED_FILES=$(git diff --name-only --staged | wc -l)
if [ "${MODIFIED_FILES}" -eq 0 ]; then
    echo 'No files have been staged for commit, aborting commit without running local hooks'
    exit 0
fi

if [ -e ./.git/hooks/pre-commit ]; then
    ./.git/hooks/pre-commit "$@"
fi

RED=$(tput setaf 160)
BOLD=$(tput bold)
RESET=$(tput sgr0)

if type kubeval > /dev/null 2>&1; 
then
    echo "Kubeval installed. Checking kubernetes manifests"
    # Finds .yml or .yaml files in a kubernetes directory and runs kubeval on all of the files
    find . -path '*/kubernetes/*' -regex ".*\\.ya*ml" -type f -exec kubeval {} +
    RETCODE=$?
    if [ $RETCODE -ne 0 ]
    then
        echo "${RED}${BOLD}ERROR:${RESET} Errors were found in kubernetes manifests. Check the output for errors/warnings."
        exit $RETCODE
    fi
fi

# vim:set et sw=4 ts=8 ft=sh:
