- name: Install kubeval tap for brew
  become: no
  homebrew_tap:
    name: instrumenta/instrumenta

- name: Install kubernetes tools via brew
  become: no
  package:
    state: latest
    name:
      - kubectl
      - kubectx
      - minikube
      - kubeval
